spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/apacheCamel?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
#    password: admin
#    username: root
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: update
#      generate-ddl: true
  application:
    name: integration_kafka_cassandra
#logging:#  level:#    root: debug

#fromRoute: kafka:inputItemTopic?brokers=localhost:9092&groupId=itemDev&autoOffsetReset=earliest&consumersCount=1
urlCassandra: cql://localhost
port: 9042
toRoute: log:?level=INFO&showBody=true
camel:
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /*